{{ range .Values.vms }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.resources.requests.memory",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 1610612736
        }
      ]
  labels:
    app: {{ .name }}
    vm.kubevirt.io/template: centos-stream9-server-medium
    vm.kubevirt.io/template.revision: "1"
    vm.kubevirt.io/template.version: v0.24.2
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: {{ .name }}
    spec:
      source:
        pvc:
          name: {{ .name }}-pvc
          namespace: {{ $.Values.namespace }}
      storage:
        resources:
          requests:
            storage: {{ .disk_size }}
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: centos-stream9
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: {{ .name}}
        kubevirt.io/size: medium
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.6.0
        resources:
          requests:
            memory: {{ .memory }}
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: {{ .name }}
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: centos
            password: ${CLOUD_USER_PASSWORD}
            chpasswd: { expire: False }
        name: cloudinitdisk
{{- end }}